### ISSUE TITLE
Issue Importing

### ISSUE THREAD

**Issue by rahb3rt** [VonStruddle/PyHunter#2]
Tried importing pyhunter, and it failed. Tried with sudo and had no problems. But then tried after again and failed. Any tips?

**Comment by PriscillaRoy** [comment]
try installing it and using it in an IDE like pycharm

**Comment by VonStruddle** [comment]
Are you importing it from a Python 3 virtual env ?

**Comment by VonStruddle** [comment]
No answers yet, closing issue ;)
