### ISSUE TITLE
Number of emails in outputted dictionary is different from number in email_count

### ISSUE THREAD

**Issue by StephenCranney** [VonStruddle/PyHunter#27]
Thanks so much for the very helpful tool. I'm trying to pull a list of emails from a website. In this case, let's use my local public library: 

`mydict=hunter.domain_search('https://www.pgcmls.info')`

To get a list of the email addresses I then calculate the length of the "emails" key

`len(mydict['emails'])`

And then cycle through, e.g.

`mydict['emails'][2]['value']`

However, I can't help but notice that the number of email tags in the dictionary is ten, whereas if I use the email_county function it tells me there are about 31 emails associated with that website. I can't help but think that there's some easy explanation that I am somehow missing. How exactly does one grab the entire list of emails?

Thanks in advance!

**Comment by VonStruddle** [comment]
Hey @StephenCranney 👋

Sorry for the late answer.

It seems that there's 40 emails for this domain. Are you sure you checked the total number of emails or just generic/personal ones?

**Comment by StephenCranney** [comment]
No problem. One of my colleagues thinks he's figured it out, so I think we're good. Thank you!
