### ISSUE TITLE
response 200 for company search 

### ISSUE THREAD

**Issue by s3afroze** [VonStruddle/PyHunter#3]
First of all thank you for making this awesome wrapper!

When I try to search for an email using company option, I get response 200 but when I search with domain,I receive an email address.
What's the problem here? Am i missing something?

Thanks,
Shahzeb

**Comment by VonStruddle** [comment]
Hey @s3afroze !

Thanks for the kind words ;)

Can you please share your code and response? I tried today on some company names and it was working for me.

Thanks!

**Comment by s3afroze** [comment]
Thanks for the quick response.

I simply copied the code from the documentation:

`hunter.email_finder(company='Instragram', full_name='Kevin Systrom', raw=True)
`
I was trying it out directly on terminal - could this be the reason? I doubt it but just wanted to let you know as much as I could.

**Comment by VonStruddle** [comment]
Yeah it's normal, if you select `raw=True`, you'll get the full response from `requests`, so you'll get the body by calling the `.json()` method. Or you can remove `raw=True` ;)

**Comment by s3afroze** [comment]
ohh I get it now. New to programming here
Thanks a lot!

**Comment by VonStruddle** [comment]
No problem dude, we all went through these steps 😉 

Closing the issue.
