### ISSUE TITLE
Add support for seniority parameter

### ISSUE THREAD

**Issue by hussainshamaas** [VonStruddle/PyHunter#45]
Hi, 

I looked at the API for domain search, looks like they added  seniority as a parameter. is this supported?

`seniority `- Get only email addresses for people with the selected seniority level. The possible values are `junior`, `senior` or `executive`. Several seniority levels can be selected (delimited by a comma).

**Comment by VonStruddle** [comment]
Hey 👋

Yeah I have to add support for `seniority` and `department`. I'll do that this week hopefully 😉

**Comment by VonStruddle** [comment]
Done with 1.4
