### ISSUE TITLE
TypeError: setdefault() takes no keyword arguments

### ISSUE THREAD

**Issue by benngarcia** [VonStruddle/PyHunter#53]
First, thanks for creating this wrapper. Trying to build this thing quickly and it's mucho appreciated.

Anyway, calling hunter.createlead(), passing 4 args, but getting an TypeError,

Relevant Error message: 
Traceback (most recent call last):
[mysupertopsecretstuffredacted], 
  File "[topsecret]/env/lib/python3.8/site-packages/pyhunter/pyhunter.py", line 318, in create_lead
    return self._query_hunter(endpoint, params, 'post', payload)
  File "[topsecret]/env/lib/python3.8/site-packages/pyhunter/pyhunter.py", line 17, in _query_hunter
    request_kwargs.setdefault(json=payload)
TypeError: setdefault() takes no keyword arguments

Gonna go ahead and just lead generation without the wrapper. I had no issues with other parts of the wrapper.

**Comment by VonStruddle** [comment]
Hey, thanks for the kind words and sorry for the delay. I'm quite busy atm.

Do you have an example of the 4 arguments? (no need to copy/paste, just show me something similar 😉)

**Comment by benngarcia** [comment]
IIRC I was doing ("Example", "Person", email="example@example.com", company="ExampleCompany") or I might've been using the website="example.com" instead of company, not entirely sure

**Comment by VonStruddle** [comment]
Fixed with https://github.com/VonStruddle/PyHunter/pull/54
