### ISSUE TITLE
python import PyHunter

### ISSUE THREAD

**Issue by jepunband** [VonStruddle/PyHunter#57]
hello is there a way whereby i do not have to do an import and run the entire command again every time i do the search?
example: 
>>> from pyhunter import PyHunter
>>> hunter = PyHunter('API_Key')
>>> hunter.email_verifier('mail@mail.com')

**Comment by VonStruddle** [comment]
Hey 👋

Not sure to understand what you mean. You want to not have to write `from pyhunter import PyHunter` ?
